<select name="country" id="country" class="text">
                          <option value="" >-- <?php echo SELECT;?> --</option>
                          <option value="1" <?php if($country==1){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_1;?></option>
                          <option value="2" <?php if($country==2){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_2;?></option>
                          <option value="3" <?php if($country==3){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_3;?></option>
                          <option value="4" <?php if($country==4){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_4;?></option>
                          <option value="5" <?php if($country==5){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_5;?></option>
                          <option value="6" <?php if($country==6){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_6;?></option>
                          <option value="7" <?php if($country==7){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_7;?></option>
                          <option value="8" <?php if($country==8){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_8;?></option>
                          <option value="9" <?php if($country==9){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_9;?></option>
                          <option value="10" <?php if($country==10){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_10;?></option>
                          <option value="11" <?php if($country==11){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_11;?></option>
                          <option value="12" <?php if($country==12){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_12;?></option>
                          <option value="13" <?php if($country==13){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_13;?></option>
                          <option value="14" <?php if($country==14){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_14;?></option>
                          <option value="15" <?php if($country==15){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_15;?></option>
                          <option value="16" <?php if($country==16){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_16;?></option>
                          <option value="17" <?php if($country==17){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_17;?></option>
                          <option value="18" <?php if($country==18){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_18;?></option>
                          <option value="19" <?php if($country==19){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_19;?></option>
                          <option value="20" <?php if($country==20){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_20;?></option>
                          <option value="21" <?php if($country==21){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_21;?></option>
                          <option value="22" <?php if($country==22){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_22;?></option>
                          <option value="23" <?php if($country==23){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_23;?></option>
                          <option value="24" <?php if($country==24){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_24;?></option>
                          <option value="25" <?php if($country==25){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_25;?></option>
                          <option value="26" <?php if($country==26){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_26;?></option>
                          <option value="27" <?php if($country==27){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_27;?></option>
                          <option value="28" <?php if($country==28){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_28;?></option>
                          <option value="29" <?php if($country==29){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_29;?></option>
                          <option value="30" <?php if($country==30){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_30;?></option>
                          <option value="31" <?php if($country==31){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_31;?></option>
                          <option value="32" <?php if($country==32){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_32;?></option>
                          <option value="33" <?php if($country==33){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_33;?></option>
                          <option value="34" <?php if($country==34){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_34;?></option>
                          <option value="35" <?php if($country==35){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_35;?></option>
                          <option value="36" <?php if($country==36){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_36;?></option>
                          <option value="37" <?php if($country==37){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_37;?></option>
                          <option value="38" <?php if($country==38){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_38;?></option>
                          <option value="39" <?php if($country==39){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_39;?></option>
                          <option value="40" <?php if($country==40){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_40;?></option>
                          <option value="41" <?php if($country==41){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_41;?></option>
                          <option value="42" <?php if($country==42){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_42;?></option>
                          <option value="43" <?php if($country==43){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_43;?></option>
                          <option value="44" <?php if($country==44){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_44;?></option>
                          <option value="45" <?php if($country==45){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_45;?></option>
                          <option value="46" <?php if($country==46){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_46;?></option>
                          <option value="47" <?php if($country==47){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_47;?></option>
                          <option value="48" <?php if($country==48){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_48;?></option>
                          <option value="49" <?php if($country==49){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_49;?></option>
                          <option value="50" <?php if($country==50){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_50;?></option>
                          <option value="51" <?php if($country==51){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_51;?></option>
                          <option value="52" <?php if($country==52){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_52;?></option>
                          <option value="53" <?php if($country==53){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_53;?></option>
                          <option value="54" <?php if($country==54){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_54;?></option>
                          <option value="55" <?php if($country==55){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_55;?></option>
                          <option value="56" <?php if($country==56){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_56;?></option>
                          <option value="57" <?php if($country==57){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_57;?></option>
                          <option value="58" <?php if($country==58){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_58;?></option>
                          <option value="59" <?php if($country==59){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_59;?></option>
                          <option value="60" <?php if($country==60){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_60;?></option>
                          <option value="61" <?php if($country==61){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_61;?></option>
                          <option value="62" <?php if($country==62){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_62;?></option>
                          <option value="63" <?php if($country==63){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_63;?></option>
                          <option value="64" <?php if($country==64){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_64;?></option>
                          <option value="65" <?php if($country==65){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_65;?></option>
                          <option value="66" <?php if($country==66){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_66;?></option>
                          <option value="67" <?php if($country==67){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_67;?></option>
                          <option value="68" <?php if($country==68){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_68;?></option>
                          <option value="69" <?php if($country==69){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_69;?></option>
                          <option value="70" <?php if($country==70){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_70;?></option>
                          <option value="71" <?php if($country==71){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_71;?></option>
                          <option value="72" <?php if($country==72){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_72;?></option>
                          <option value="73" <?php if($country==73){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_73;?></option>
                          <option value="74" <?php if($country==74){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_74;?></option>
                          <option value="75" <?php if($country==75){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_75;?></option>
                          <option value="76" <?php if($country==76){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_76;?></option>
                          <option value="77" <?php if($country==77){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_77;?></option>
                          <option value="78" <?php if($country==78){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_78;?></option>
                          <option value="79" <?php if($country==79){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_79;?></option>
                          <option value="80" <?php if($country==80){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_80;?></option>
                          <option value="81" <?php if($country==81){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_81;?></option>
                          <option value="82" <?php if($country==82){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_82;?></option>
                          <option value="83" <?php if($country==83){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_83;?></option>
                          <option value="84" <?php if($country==84){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_84;?></option>
                          <option value="85" <?php if($country==85){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_85;?></option>
                          <option value="86" <?php if($country==86){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_86;?></option>
                          <option value="87" <?php if($country==87){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_87;?></option>
                          <option value="88" <?php if($country==88){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_88;?></option>
                          <option value="89" <?php if($country==89){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_89;?></option>
                          <option value="90" <?php if($country==90){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_90;?></option>
                          <option value="91" <?php if($country==91){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_91;?></option>
                          <option value="92" <?php if($country==92){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_92;?></option>
                          <option value="93" <?php if($country==93){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_93;?></option>
                          <option value="94" <?php if($country==94){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_94;?></option>
                          <option value="95" <?php if($country==95){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_95;?></option>
                          <option value="96" <?php if($country==96){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_96;?></option>
                          <option value="97" <?php if($country==97){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_97;?></option>
                          <option value="98" <?php if($country==98){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_98;?></option>
                          <option value="99" <?php if($country==99){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_99;?></option>
                          <option value="100" <?php if($country==100){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_100;?></option>
                          <option value="101" <?php if($country==101){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_101;?></option>
                          <option value="102" <?php if($country==102){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_102;?></option>
                          <option value="103" <?php if($country==103){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_103;?></option>
                          <option value="104" <?php if($country==104){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_104;?></option>
                          <option value="105" <?php if($country==105){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_105;?></option>
                          <option value="106" <?php if($country==106){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_106;?></option>
                          <option value="107" <?php if($country==107){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_107;?></option>
                          <option value="108" <?php if($country==108){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_108;?></option>
                          <option value="109" <?php if($country==109){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_109;?></option>
                          <option value="110" <?php if($country==110){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_110;?></option>
                          <option value="111" <?php if($country==111){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_111;?></option>
                          <option value="112" <?php if($country==112){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_112;?></option>
                          <option value="113" <?php if($country==113){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_113;?></option>
                          <option value="114" <?php if($country==114){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_114;?></option>
                          <option value="115" <?php if($country==115){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_115;?></option>
                          <option value="116" <?php if($country==116){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_116;?></option>
                          <option value="117" <?php if($country==117){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_117;?></option>
                          <option value="118" <?php if($country==118){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_118;?></option>
                          <option value="119" <?php if($country==119){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_119;?></option>
                          <option value="120" <?php if($country==120){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_120;?></option>
                          <option value="121" <?php if($country==121){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_121;?></option>
                          <option value="122" <?php if($country==122){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_122;?></option>
                          <option value="123" <?php if($country==123){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_123;?></option>
                          <option value="124" <?php if($country==124){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_124;?></option>
                          <option value="125" <?php if($country==125){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_125;?></option>
                          <option value="126" <?php if($country==126){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_126;?></option>
                          <option value="127" <?php if($country==127){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_127;?></option>
                          <option value="128" <?php if($country==128){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_128;?></option>
                          <option value="129" <?php if($country==129){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_129;?></option>
                          <option value="130" <?php if($country==130){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_130;?></option>
                          <option value="131" <?php if($country==131){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_131;?></option>
                          <option value="132" <?php if($country==132){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_132;?></option>
                          <option value="133" <?php if($country==133){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_133;?></option>
                          <option value="134" <?php if($country==134){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_134;?></option>
                          <option value="135" <?php if($country==135){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_135;?></option>
                          <option value="136" <?php if($country==136){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_136;?></option>
                          <option value="137" <?php if($country==137){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_137;?></option>
                          <option value="138" <?php if($country==138){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_138;?></option>
                          <option value="139" <?php if($country==139){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_139;?></option>
                          <option value="140" <?php if($country==140){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_140;?></option>
                          <option value="141" <?php if($country==141){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_141;?></option>
                          <option value="142" <?php if($country==142){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_142;?></option>
                          <option value="143" <?php if($country==143){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_143;?></option>
                          <option value="144" <?php if($country==144){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_144;?></option>
                          <option value="145" <?php if($country==145){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_145;?></option>
                          <option value="146" <?php if($country==146){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_146;?></option>
                          <option value="147" <?php if($country==147){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_147;?></option>
                          <option value="148" <?php if($country==148){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_148;?></option>
                          <option value="149" <?php if($country==149){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_149;?></option>
                          <option value="150" <?php if($country==150){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_150;?></option>
                          <option value="151" <?php if($country==151){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_151;?></option>
                          <option value="152" <?php if($country==152){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_152;?></option>
                          <option value="153" <?php if($country==153){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_153;?></option>
                          <option value="154" <?php if($country==154){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_154;?></option>
                          <option value="155" <?php if($country==155){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_155;?></option>
                          <option value="156" <?php if($country==156){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_156;?></option>
                          <option value="157" <?php if($country==157){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_157;?></option>
                          <option value="158" <?php if($country==158){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_158;?></option>
                          <option value="159" <?php if($country==159){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_159;?></option>
                          <option value="160" <?php if($country==160){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_160;?></option>
                          <option value="161" <?php if($country==161){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_161;?></option>
                          <option value="162" <?php if($country==162){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_162;?></option>
                          <option value="163" <?php if($country==163){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_163;?></option>
                          <option value="164" <?php if($country==164){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_164;?></option>
                          <option value="165" <?php if($country==165){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_165;?></option>
                          <option value="166" <?php if($country==166){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_166;?></option>
                          <option value="167" <?php if($country==167){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_167;?></option>
                          <option value="168" <?php if($country==168){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_168;?></option>
                          <option value="169" <?php if($country==169){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_169;?></option>
                          <option value="170" <?php if($country==170){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_170;?></option>
                          <option value="171" <?php if($country==171){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_171;?></option>
                          <option value="172" <?php if($country==172){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_172;?></option>
                          <option value="173" <?php if($country==173){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_173;?></option>
                          <option value="174" <?php if($country==174){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_174;?></option>
                          <option value="175" <?php if($country==175){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_175;?></option>
                          <option value="176" <?php if($country==176){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_176;?></option>
                          <option value="177" <?php if($country==177){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_177;?></option>
                          <option value="178" <?php if($country==178){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_178;?></option>
                          <option value="179" <?php if($country==179){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_179;?></option>
                          <option value="180" <?php if($country==180){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_180;?></option>
                          <option value="181" <?php if($country==181){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_181;?></option>
                          <option value="182" <?php if($country==182){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_182;?></option>
                          <option value="183" <?php if($country==183){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_183;?></option>
                          <option value="184" <?php if($country==184){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_184;?></option>
                          <option value="185" <?php if($country==185){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_185;?></option>
                          <option value="186" <?php if($country==186){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_186;?></option>
                          <option value="187" <?php if($country==187){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_187;?></option>
                          <option value="188" <?php if($country==188){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_188;?></option>
                          <option value="189" <?php if($country==189){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_189;?></option>
                          <option value="190" <?php if($country==190){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_190;?></option>
                          <option value="191" <?php if($country==191){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_191;?></option>
                          <option value="192" <?php if($country==192){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_192;?></option>
                          <option value="193" <?php if($country==193){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_193;?></option>
                          <option value="194" <?php if($country==194){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_194;?></option>
                          <option value="195" <?php if($country==195){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_195;?></option>
                          <option value="196" <?php if($country==196){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_196;?></option>
                          <option value="197" <?php if($country==197){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_197;?></option>
                          <option value="198" <?php if($country==198){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_198;?></option>
                          <option value="199" <?php if($country==199){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_199;?></option>
                          <option value="200" <?php if($country==200){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_200;?></option>
                          <option value="201" <?php if($country==201){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_201;?></option>
                          <option value="202" <?php if($country==202){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_202;?></option>
                          <option value="203" <?php if($country==203){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_203;?></option>
                          <option value="204" <?php if($country==204){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_204;?></option>
                          <option value="205" <?php if($country==205){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_205;?></option>
                          <option value="206" <?php if($country==206){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_206;?></option>
                          <option value="207" <?php if($country==207){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_207;?></option>
                          <option value="208" <?php if($country==208){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_208;?></option>
                          <option value="209" <?php if($country==209){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_209;?></option>
                          <option value="210" <?php if($country==210){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_210;?></option>
                          <option value="211" <?php if($country==211){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_211;?></option>
                          <option value="212" <?php if($country==212){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_212;?></option>
                          <option value="213" <?php if($country==213){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_213;?></option>
                          <option value="214" <?php if($country==214){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_214;?></option>
                          <option value="215" <?php if($country==215){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_215;?></option>
                          <option value="216" <?php if($country==216){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_216;?></option>
                          <option value="217" <?php if($country==217){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_217;?></option>
                          <option value="218" <?php if($country==218){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_218;?></option>
                          <option value="219" <?php if($country==219){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_219;?></option>
                          <option value="220" <?php if($country==220){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_220;?></option>
                          <option value="221" <?php if($country==221){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_221;?></option>
                          <option value="222" <?php if($country==222){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_222;?></option>
                          <option value="223" <?php if($country==223 || $country==""){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_223;?></option>
                          <option value="224" <?php if($country==224){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_224;?></option>
                          <option value="225" <?php if($country==225){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_225;?></option>
                          <option value="226" <?php if($country==226){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_226;?></option>
                          <option value="227" <?php if($country==227){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_227;?></option>
                          <option value="228" <?php if($country==228){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_228;?></option>
                          <option value="229" <?php if($country==229){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_229;?></option>
                          <option value="230" <?php if($country==230){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_230;?></option>
                          <option value="231" <?php if($country==231){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_231;?></option>
                          <option value="232" <?php if($country==232){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_232;?></option>
                          <option value="233" <?php if($country==233){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_233;?></option>
                          <option value="234" <?php if($country==234){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_234;?></option>
                          <option value="235" <?php if($country==235){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_235;?></option>
                          <option value="236" <?php if($country==236){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_236;?></option>
                          <option value="237" <?php if($country==237){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_237;?></option>
                          <option value="238" <?php if($country==238){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_238;?></option>
                          <option value="239" <?php if($country==239){ echo "selected=\"selected\""; }?>><?php echo COUNTRY_239;?></option>
                        </select>
